Server:
  ResourcePack:
    # The ResourcePack URL. This must be a direct URL, ending with .zip. For Dropbox URLs, add ?dl=1 to the end.
    url: https://faithfulpack.com/dl/104/
    # Use a site such as http://onlinemd5.com/ or the hash provided when uploading to https://mc-packs.net/.
    hash: BA52452AD77CAAA7530876950C8E2D020699EBDD
  Actions:
    # To disable commands, you can do Command: []
    # List of valid actions: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerResourcePackStatusEvent.Status.html
    ACCEPTED:
      kick: false
      Commands:
        - say [player] accepted the resource pack!
    DECLINED:
      kick: true
      Commands:
        - say [player] denied the resource pack!
    FAILED_DOWNLOAD:
      kick: true
      Commands:
        - say [player] failed to download the resource pack!
  # Speed in ticks at which the ResourcePack prompt will be resent to the player (prevents escaping out)
  Update GUI Speed: 20
  # Whether to re-send the GUI. This may cause issues with newer clients, so it is disabled by default.
  Update GUI: false
  # Should the plugin verify your URL + hash?
  verify: true
  # Should we resend the resource pack on reload? Any players that have already accepted will receive the updated one.
  resend: true
  # Whether to ignore geyser players. Only enable this if you use geyser.
  #  Java clients can spoof this and bypass the ResourcePack!
  geyser: false
  # Whether to enable debug mode. Prints some extra info.
  debug: false