# If this is enabled, the plugin will be used purely for further compatibility with your Velocity proxy.
# This is required for the prevent-movement feature.
# Actions (excluding kicks) will still take place. Bypass permissions will also still be enabled.
velocity-mode: false

# If this is true, movement will be prevented until the resource pack is loaded.
prevent-movement: true

Server:
  ResourcePack:
    # The ResourcePack URL. This must be a direct URL, ending with .zip. For Dropbox URLs, add ?dl=1 to the end.
    url: https://www.convallyria.com/files/BlankPack.zip
    # Whether to automatically generate the SHA-1 hash. This is not recommended for security and reliability.
    # The hash setting will be ignored if this is true, however it will fall back to that if the generation fails.
    generate-hash: false
    # Use a site such as http://onlinemd5.com/ or the hash provided when uploading to https://mc-packs.net/.
    hash: 118AFFFC54CDCD308702F81BA24E03223F15FE5F

  Actions:
    # To disable commands, you can do Command: []
    # List of valid actions: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerResourcePackStatusEvent.Status.html
    ACCEPTED:
      kick: false
      Commands:
        - say [player] accepted the resource pack!
    DECLINED:
      kick: true
      Commands:
        - say [player] denied the resource pack!
    FAILED_DOWNLOAD:
      kick: true
      Commands:
        - say [player] failed to download the resource pack!
  # Speed in ticks at which the ResourcePack prompt will be resent to the player (prevents escaping out)
  Update GUI Speed: 20
  # Whether to re-send the GUI. This will only update for clients <= 1.12. (requires ViaVersion)
  Update GUI: true
  # Should the plugin verify your URL + hash?
  verify: true
  # Should we resend the resource pack on reload? Any players that have already accepted will receive the updated one.
  resend: true
  # Should we forcefully send a resource pack that has an invalid size for the player's client version? (requires ViaVersion)
  force-invalid-size: false
  # Whether to ignore geyser players. Only enable this if you use geyser.
  #  Java clients can spoof this and bypass the ResourcePack!
  geyser: false
  # Whether to enable the bypass permission. If you disable this, all OPs will no longer be able to bypass.
  # But you should really fix your permissions instead.
  bypass-permission: true
  # Whether to enable debug mode. Prints some extra info.
  debug: false