# ForcePack Velocity config.
# ForcePack uses MiniMessage for message formatting.
# You can check the MiniMessage documentation for how to use it: https://docs.adventure.kyori.net/minimessage#format
# Need help? Join our Discord: https://discord.gg/fh62mxU

# Whether to ignore geyser players. Only enable this if you use geyser.
#  Java clients can spoof this and bypass the ResourcePack!
geyser = false

# Whether to verify that your resource packs have the correct hash.
# May reduce startup time, but makes problems less obvious and can be a security risk.
verify-resource-packs = true

# If we should continuously update the GUI for players <= 1.12. Prevents escaping out bypass.
update-gui = true

# The update speed of the GUI in milliseconds
update-gui-speed = 1000

# Should we forcefully send a resource pack that has an invalid size for the player's client version?
force-invalid-size = false

# Whether to enable the bypass permission. If you disable this, all OPs will no longer be able to bypass.
# But you should really fix your permissions instead.
bypass-permission = true

# Whether to enable debug mode. Prints some extra info.
debug = false

[unload-pack]
    # Whether to send an empty ResourcePack when joining a server without one configured, and the player has one applied
    enable = true
    # The URL of the unload pack
    url = "https://www.convallyria.com/files/BlankPack.zip"
    # The SHA-1 hash of the unload pack file
    hash = "118AFFFC54CDCD308702F81BA24E03223F15FE5F"

[global-pack]
    # Whether to enable a global resource pack. If a server does not have a resource pack configured, it shall use this.
    enable = false
    # The URL of the global pack
    url = "https://www.convallyria.com/files/BlankPack.zip"
    # The SHA-1 hash of the global pack file
    hash = "118AFFFC54CDCD308702F81BA24E03223F15FE5F"
    # The prompt message for clients on 1.17+.
    resourcepack.prompt = "<yellow>Please accept our resource pack to improve your experience."

    [global-pack.actions]
        # List of valid actions: https://jd.velocitypowered.com/3.0.0/com/velocitypowered/api/event/player/PlayerResourcePackStatusEvent.Status.html
        [global-pack.actions.ACCEPTED]
            kick = false
            commands = []
        [global-pack.actions.DECLINED]
            kick = true
            message = "<color:#FF5555>Please accept our ResourcePack to play on the server!"
            commands = []
        [global-pack.actions.FAILED_DOWNLOAD]
            kick = true
            message = "<color:#FF5555>The ResourcePack download failed. Please try rejoining."
            commands = []
        [global-pack.actions.SUCCESSFUL]
            kick = false
            commands = []

[servers]
    # You can specify any server name here that is configured in velocity.
    [servers.build]
        # The ResourcePack URL. This must be a direct URL, ending with .zip. For Dropbox URLs, add ?dl=1 to the end.
        resourcepack.url = "https://www.convallyria.com/files/BlankPack.zip"
        # Whether to automatically generate the SHA-1 hash. This is not recommended for security and reliability.
        # The hash setting will be ignored if this is true, however it will fall back to that if the generation fails.
        resourcepack.generate-hash = false
        # Use a site such as http://onlinemd5.com/ or the hash provided when uploading to https://mc-packs.net/.
        resourcepack.hash = "118AFFFC54CDCD308702F81BA24E03223F15FE5F"
        # The prompt message for clients on 1.17+.
        resourcepack.prompt = "<yellow>Please accept our resource pack to improve your experience."
        [servers.build.actions]
            # List of valid actions: https://jd.velocitypowered.com/3.0.0/com/velocitypowered/api/event/player/PlayerResourcePackStatusEvent.Status.html
            [servers.build.actions.ACCEPTED]
                kick = false
                commands = []
            [servers.build.actions.DECLINED]
                kick = true
                message = "<color:#FF5555>Please accept our ResourcePack to play on the server!"
                commands = []
            [servers.build.actions.FAILED_DOWNLOAD]
                kick = true
                message = "<color:#FF5555>The ResourcePack download failed. Please try rejoining."
                commands = []
            [servers.build.actions.SUCCESSFUL]
                kick = false
                commands = []





